version: "3.9"
services:
  web:
    image: composetest_web
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"
  wordpress:
    image: uyosep2/wpstudy:1.0
    hostname: wp
    ports:
      - "7777:80"
      - "8080:80"
      - "8081:443"
    depends_on:
      - mysql
    environment:
      - WORDPRESS_DB_PASSWORD=1234
    links:
      - mysql
  mysql:
    image: uyosep2/dbstudy:1.0
    hostname: db
    volumes:
      - /root/composetest/db:/var/lib/mysql
    environment:
      - MYSQL_DB_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
  template:
    image: uyosep2base:1.2
    hostname: template
    ports:
      - "9000:80"
